---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE(cloudnull): When the machinectl backend is set the container create
#                  module will use the "machinectl" container template which
#                  will build and store all containers using a copy-on-write
#                  snapshot from the base image stored withine machinectl.
- name: Create container (machinectl)
  lxc_container:
    name: "{{ inventory_hostname }}"
    container_log: true
    container_log_level: "{{ (debug | bool) | ternary('DEBUG', 'INFO') }}"
    config: "{{ lxc_container_config }}"
    template: "machinectl"
    state: started
    template_options: "{{ lxc_container_machinectl_template_options }}"
  delegate_to: "{{ physical_host }}"
